wolfenrain/umbra

.github/CODEOWNERS
.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/ci.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/performance.md
.github/ISSUE_TEMPLATE/refactor.md
.github/ISSUE_TEMPLATE/revert.md
.github/ISSUE_TEMPLATE/style.md
.github/ISSUE_TEMPLATE/test.md
.github/workflows/app.yaml
.github/workflows/ci.yaml

Setup more GitHub related files.

chore: setup more GitHub related files

---

packages/umbra_flutter/pubspec.yaml

docs: `umbra_flutter` description

---

packages/umbra_cli/pubspec.yaml
tools/release_ready.sh

chore: after release

---

docs/getting-started/3-next-steps.md

docs: link to `umbra_flutter`

---

packages/umbra_cli/lib/src/commands/create/create.dart
packages/umbra_cli/lib/src/commands/generate/generate.dart
packages/umbra_cli/lib/src/commands/install_deps.dart
packages/umbra_cli/lib/src/commands/update.dart
packages/umbra_cli/pubspec.yaml
packages/umbra_cli/test/helpers/with_runner.dart
packages/umbra_cli/test/src/commands/create/create_test.dart
packages/umbra_cli/test/src/commands/generate/generate_test.dart
packages/umbra_cli/test/src/commands/install_deps_test.dart
packages/umbra_cli/test/src/commands/update_test.dart

Upgrade Mason and switch to the new Progress API.

chore(umbra_cli): upgrade mason

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.2

---

docs/shader-specifications/2-uniforms.md
packages/umbra_flutter/example/.metadata

docs: add resolution information

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.3

---

packages/umbra/CHANGELOG.md
packages/umbra/pubspec.yaml

chore(umbra): v0.1.0-dev.2

---

packages/umbra_flutter/CHANGELOG.md
packages/umbra_flutter/pubspec.yaml

chore(umbra_flutter): v0.1.0-dev.2

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.4

---

packages/umbra_cli/pubspec.yaml
tools/release_ready.sh

chore: after release changes

---

docs/cli-commands.md

Update the docs to reflect the new generate type.

docs: update CLI commands

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.5

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.6

---

packages/umbra/CHANGELOG.md
packages/umbra/pubspec.yaml

chore(umbra): v0.1.0-dev.3

---

packages/umbra_flutter/CHANGELOG.md
packages/umbra_flutter/pubspec.yaml

chore(umbra_flutter): v0.1.0-dev.3

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.7

---

packages/umbra/CHANGELOG.md
packages/umbra/pubspec.yaml

chore(umbra): v0.1.0-dev.4

---

packages/umbra_flutter/CHANGELOG.md
packages/umbra_flutter/pubspec.yaml

chore(umbra_flutter): v0.1.0-dev.4

---

packages/umbra_cli/CHANGELOG.md
packages/umbra_cli/lib/src/version.dart
packages/umbra_cli/pubspec.yaml

chore(umbra_cli): v0.1.0-dev.8
